backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\helpers\Url;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\GiftCardsForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $reservationForm = new ContactForm();
        
        if ($reservationForm->load(Yii::$app->request->post()) && $reservationForm->validate()) {
            if ($reservationForm->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('index', [
                'reservationsForm' => $reservationForm,
                'giftCardsForm' => new GiftCardsForm()
            ]);
        }
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionCards()
    {
        $model = new GiftCardsForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }
        }

        return $this->redirect(Url::to(['site/index']));
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/views/site/about.php
<!-- BEGIN ABOUT SECTION -->
<section id="about" class="section about">
    <div class="container">
        <div class="jt_row jt_row-fluid row">
            <div class="col-md-12 jt_col column_container">
                <h2 class="section-title">About Us</h2>
            </div> 
            <div class="col-md-6 col-md-offset-3 jt_col column_container">    
                <div class="section-subtitle">
                    We love restaurants as much as you do. That’s why we’ve been helping them fill tables since 1999. Welcome to elixir restaurant 
                </div>
            </div>


            <div class="col-md-6 jt_col column_container">
                <h2 class="heading font-smoothing">The History</h2>
                <p class="text">
                    The <strong>History of Kitchens</strong> and Cooks gives further intimation on Mr Boulanger 
                    usual menu, stating confidently that "Boulanger served salted poultry and 
                    fresh eggs, all presented without a tablecloth on small marble tables". 
                    Numerous commentators have also referred to the supposed restaurant 
                    owner's eccentric habit of touting for custom outside his establishment, 
                    dressed in aristocratic fashion and brandishing a sword
                </p>
                <p class="text">
                    According to Miss Spang, there is not a shred of evidence for any of it. 
                    She said: These legends just get passed on by hearsay and then spiral 
                    out of control. Her interest in <strong>Boulanger</strong> dates back to a history of 
                    food seminar in Paris in the mid-1990s
                </p>
                
                <div class="ornament"></div>
            </div>  

            <div class="col-md-6 jt_col column_container">
            <div class="voffset40"></div>
                <div id="owl-about" class="owl-carousel">
                        <div class="item"><img src="images/about01.jpg" alt=""></div>
                        <div class="item"><img src="images/about02.jpg" alt=""></div>
                        <div class="item"><img src="images/about03.jpg" alt=""></div>
                </div>
            </div> 
        </div>
        <!-- <div class="jt_row jt_row-fluid row">
            <div class="col-md-6 jt_col column_container">
                <div class="voffset10"></div>
                <div id="owl-about2" class="owl-carousel">
                        <div class="item"><img src="images/about04.jpg" alt=""></div>
                        <div class="item"><img src="images/about05.jpg" alt=""></div>
                        <div class="item"><img src="images/about06.jpg" alt=""></div>
                </div>
            </div>  



            <div class="col-md-6 jt_col column_container">

                <p class="text">
                    The <strong>History of Kitchens</strong> and Cooks gives further intimation on Mr Boulanger 
                    usual menu, stating confidently that "Boulanger served salted poultry and 
                    fresh eggs, all presented without a tablecloth on small marble tables". 
                    Numerous commentators have also referred to the supposed restaurant 
                    owner's eccentric habit of touting for custom outside his establishment, 
                    dressed in aristocratic fashion and brandishing a sword
                </p>
                <p class="text">
                    According to Miss Spang, there is not a shred of evidence for any of it. 
                    She said: These legends just get passed on by hearsay and then spiral 
                    out of control. Her interest in <strong>Boulanger</strong> dates back to a history of 
                    food seminar in Paris in the mid-1990s
                </p>
            </div> 
        </div> -->

    </div>
    
</section>
<!-- END ABOUT SECTION -->

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/gallery.php
 <!-- BEGIN GALLERY SECTION -->
 <section id="gallery" class="section gallery dark">
    <div class="jt_row jt_row-fluid row">
        <div class="col-md-12 jt_col column_container">
                <h2 class="section-title">Gallery</h2>
                <div class="col-md-6 col-md-offset-3 jt_col column_container">    
                    <div class="section-subtitle">
                        If a picture says a thousand words, then you can imagine how long it would take to describe all our selections. 
                    </div>
        </div>
                
        </div> 

        <div class="col-md-12 jt_col column_container">

            <nav class="primary">
                <ul>
                    <li><a href="#" data-filter="*" class="selected"><span>All photos</span></a></li>
                    <li><a href="#" data-filter=".dishes"><span>Dishes</span></a></li>
                    <li><a href="#" data-filter=".beer"><span>Beer</span></a></li>
                    <li><a href="#" data-filter=".interior"><span>Interior</span></a></li>
                    <li><a href="#" data-filter=".staff"><span>Staff</span></a></li>
                </ul>
            </nav>

            <div class="portfolio">

                <article class="entry dishes">
                    <img src="images/gallery/01.jpg" class="img-responsive" alt=""/>
                </article>
            
                <article class="entry dishes">
                    <img src="images/gallery/02.jpg" class="img-responsive" alt=""/>
                </article>
            
                <article class="entry dishes">
                    <img src="images/gallery/03.jpg" class="img-responsive" alt=""/>
                </article>
            
                <article class="entry interior">
                    <img src="images/gallery/08.jpg" class="img-responsive" alt=""/>
                </article>
            
                <article class="entry interior">
                    <img src="images/gallery/09.jpg" class="img-responsive" alt=""/>
                </article>
            
                <article class="entry interior">
                    <img src="images/gallery/10.jpg" class="img-responsive" alt=""/>
                </article>
            
                <article class="entry interior">
                    <img src="images/gallery/11.jpg" class="img-responsive" alt=""/>
                </article>
            
                <article class="entry beer">
                    <img src="images/gallery/12.jpg" class="img-responsive" alt=""/>
                </article>
                
                <article class="entry beer">
                    <img src="images/gallery/14.jpg" class="img-responsive" alt=""/>
                </article>
                
                <article class="entry staff">
                    <img src="images/gallery/20.jpg" class="img-responsive" alt=""/>
                </article>
                
                <article class="entry staff">
                    <img src="images/gallery/21.jpg" class="img-responsive" alt=""/>
                </article>
                
                <article class="entry beer">
                    <img src="images/gallery/18.jpg" class="img-responsive" alt=""/>
                </article>

            </div>
        </div> <!-- End .jt_col -->
    </div> <!-- End .jt_row -->
</section>
<!-- END GALLERY SECTION -->

frontend/views/site/giftCards.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;

?>

<section id="gift-cards" class="section">
    <div class="container">
            <div class="jt_row jt_row-fluid row">
                <div class="col-md-12 jt_col column_container">
                    <h2 class="section-title">Gift cards</h2>
                </div>

                <div class="col-md-6 jt_col column_container">

                <?php $form = ActiveForm::begin(['id' => 'gift-cards-form', 'method' => 'post', 'action' => Url::to(['site/cards'])]) ?>

                    <div class="col-md-10 col-md-offset-1 jt_col column_container">
                        <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>
                        <?= $form->field($model, 'phone')->textInput() ?>
                        <?= $form->field($model, 'email')->textInput() ?>
                        <?= $form->field($model, 'amount')->textInput() ?>
                        <span>The minimum amount - 30 euros</span>
                    </div>
                    <div class="col-md-4 col-md-offset-4 jt_col column_container">
                    <div class="formSent"><strong>Your Message Has Been Sent!</strong> Thank you for contacting us.</div>     
                        <?= Html::submitButton('Order', ['class' => 'button center']) ?>
                    </div>

                <?php ActiveForm::end(); ?>
                </div>

                <div class="col-md- jt_col column_container">
                    <img src="images/gift_cards.jpg">
                </div>
                <div class="voffset60"></div>
            </div>
    </div>
</section>

frontend/views/site/index.php
<?php

    use yii\helpers\Html;

    /* @var $this yii\web\View */

    $this->title = 'Duvel\'s Gastro Pub';

?>

<?= $this->render('slider') ?>

<?= $this->render('giftCards', ['model' => $giftCardsForm]) ?>

<?= $this->render('menu') ?>

<?= $this->render('gallery') ?>

<?= $this->render('reservations', ['model' => $reservationsForm]) ?>
       
<?= $this->render('location') ?>

frontend/views/site/location.php
<!-- BEGIN MAP SECTION -->
<section id="location" class="">
    <div class="col-md-12 jt_col column_container">
        <h2 class="section-title">Location</h2>
    </div> 
    <div class="col-md-12 jt_col column_container">
        <h3 class="reservation-phone">Meistaru ielā 10/12 Riga, Latvia</h3>
        <h3 class="reservation-phone">info@gastropubriga.lv</h3>
        <h3 class="reservation-phone">+371 67 225 436</h3>
        <div class="voffset50"></div>
    </div> 
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&key=AIzaSyCv-0eVCQrwle-PpkBANIYYCIV5JXq_Zt0"></script>
    <div class="map-content">
        <div class="wpgmappity_container inner-map" id="wpgmappitymap"></div>
    </div>
</section>
<!-- END MAP SECTION -->

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/menu.php
<!-- BEGIN GALLERY SECTION -->
<section id="menu" class="section">
    <div class="jt_row jt_row-fluid row">
        <div class="col-md-12 jt_col column_container">
            <h2 class="section-title">Menu</h2>
            <!-- <div class="col-md-6 col-md-offset-3 jt_col column_container">    
                <div class="section-subtitle">
                    Menu will be available in the near future
                </div>
            </div> -->
        </div> 

        <div class="col-md-12 jt_col column_container">
            <h2 class="text-center" style="margin-bottom: 30px;">Food</h2>
            <nav class="primary">
                <ul>
                    <li><a href="/docs/beer_snacks.pdf" target="_blank"><span>Beer snacks</span></a></li>
                    <li><a href="/docs/hot_snacks.pdf" target="_blank"><span>Hot Snacks & Salads</span></a></li>
                    <li><a href="/docs/snacks.pdf" target="_blank"><span>Snacks</span></a></li>
                    <li><a href="/docs/soups.pdf" target="_blank"><span>Soups & Pastas</span></a></li>
                    <li><a href="/docs/ribs.pdf" target="_blank"><span>BBQ Ribs & Burgers</span></a></li>
                </ul>
            </nav>
            <nav class="primary">
                <ul>
                    <li><a href="/docs/main.pdf" target="_blank"><span>Main</span></a></li>
                    <li><a href="/docs/grill.pdf" target="_blank"><span>Cooked on coals</span></a></li>
                    <li><a href="/docs/mussels.pdf" target="_blank"><span>Mussels and fish courses</span></a></li>
                    <li><a href="/docs/sides_and_deserts.pdf" target="_blank"><span>Sides, sauses & deserts</span></a></li>
                    <li><a href="/docs/pizza.pdf" target="_blank"><span>Pizza</span></a></li>
                </ul>
            </nav>
            <h2 class="text-center" style="margin-bottom: 30px;">Drinks</h2>
            <nav class="primary">
                <ul>
                    <li><a href="/docs/bottled_beer.pdf" target="_blank"><span>Bottled beer</span></a></li>
                    <li><a href="/docs/bottled_beer_2.pdf" target="_blank"><span>Bottled beer 2</span></a></li>
                    <li><a href="/docs/draft_beer.pdf" target="_blank"><span>Draft beer</span></a></li>
                    <li><a href="/docs/strong.pdf" target="_blank"><span>Strong</span></a></li>
                    <li><a href="/docs/cocktails.pdf" target="_blank"><span>Cocktails</span></a></li>
                    <li><a href="/docs/wine.pdf" target="_blank"><span>Wine</span></a></li>
                    <li><a href="/docs/non-alcoholic.pdf" target="_blank"><span>Non-alcoholic</span></a></li>
                </ul>
            </nav>
        </div> 
    </div> 
</section>

            

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/slider.php
<!-- BEGIN HOME SLIDER SECTION -->
<section id="home-slider">
    <div class="overlay"></div>
    <!-- SLIDER IMAGES -->
    <div id="owl-main" class="owl-carousel">
        <div class="item"><img src="images/slider/01.jpg" alt="Slide 02"></div>
    </div>
    <!-- SLIDER CONTENT -->
    <div class="slide-content">
        <!-- <div class="voffset100"></div>
        <img src="images/logo_full.png" width="30%%"> -->
        <!-- <span class="logointro"></span> -->
        <!-- <div id="owl-main-text" class="owl-carousel">
            <div class="item">
                <h2>Gastro Pub Duvels</h2>
            </div>
            <div class="item">
                <h2>Welcome to restaurant</h2>
            </div>
            <div class="item">
                <h2>Elixir exclusively food</h2>
            </div>
        </div>
        <div class="slide-sep"></div>
        <p>The Chef creates divine combinations</p> -->
    </div>
    <!-- BOTTOM ANIMATED ARROW -->
    <a href="#about" class="page-scroll menu-item"><div class="mouse"><span></span></div></a>
</section>
<!-- END HOME SLIDER SECTION -->

frontend/views/site/special_offers.php
 <!-- BEGIN MENU SECTION -->
 <section id="special-offers" class="section offers dark">

    <div class="container">
                <div class="voffset50"></div>
            <div class="jt_row jt_row-fluid row">
                <div class="col-md-12 jt_col column_container">
                    <h2 class="section-title">Lunch / Dinner / Special events / Corporative events</h2>
                </div>
                <div class="col-md-8 jt_col column_container"> 
                <img src="images/merry_xmas.jpg" />
                </div>   
                <div class="col-md-4 jt_col column_container"> 
                <div class="section-subtitle">
                    Make a reservation until 25.11.2018 and receive a 10% discount on the special offer.<br />
                    Offer valid from monday to thursday.
                </div>
                </div>
                <h2 class="text-center"><a href="/docs/xmas_menu.pdf" target="_blank">BANQUET MENU</a></h2>
                <div class="voffset50"></div>
                <h2 class="text-center"><a href="#reservations">RESERVATIONS</a></h2>
            </div>
    </div>
    <div class="voffset30"></div>
</section>
<!-- END MENU SECTION -->

frontend/views/site/working_hours.php
<!-- BEGIN TIMETABLE SECTION -->
<section id="timetable" class="section timetable parallax">
    <div class="container">
            <div class="jt_row jt_row-fluid row">
                <span class="column-divider"></span>
                <div class="col-md-12 jt_col column_container">
                    <h2 class="section-title"><span class="timetable-decorator"></span><span class="opening-hours">Opening Hours</span><span class="timetable-decorator2"></span></h2>
                </div> 
                <div class="col-md-12 jt_col column_container">    
                    <div class="section-subtitle">
                        Call For Reservations
                    </div>
                </div>
                
                <div class="col-md-3 col-md-offset-3 jt_col column_container">    
                    <div class="section-subtitle days">
                        Sunday to Tuesday
                    </div>
                    <div class="section-subtitle hours">
                        09:00<br>24:00
                    </div>
                </div>

                
                <div class="col-md-3 jt_col column_container">    
                    <div class="section-subtitle days">
                        Friday and Saturday
                    </div>
                    <div class="section-subtitle hours">
                        08:00<br>03:00
                    </div>
                </div>
                <div class="col-md-12 jt_col column_container">    
                    <div class="number">
                        RESERVATION NUMBER: 0842-5484214
                    </div>
                </div>

            </div>
    </div>
</section>
<!-- END TIMETABLE SECTION -->